name: tivele
description: A new Flutter application.

version: 1.2.2+4

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http_interceptor: ^1.0.2
  uuid: ^3.0.4
  modal_progress_hud:
  shared_preferences: ^0.5.7+3
  loadmore: ^1.0.4
  cupertino_icons: ^1.0.0
  geocoding: ^2.0.1
  font_awesome_flutter: ^8.11.0
  mask_text_input_formatter: ^1.2.1
  mime: ^0.9.7
  json_annotation: ^4.0.1
  file_picker: ^4.0.1
  google_maps_flutter: ^2.0.6
  flutter_polyline_points: ^0.2.0
  provider: ^5.0.0
  image_picker: ^0.8.4
  fluttertoast: ^8.0.8
  tinycolor: ^1.0.2
  geolocator: ^7.6.0
  google_sign_in: 4.5.9
  loading_overlay: ^0.2.1
  google_fonts: ^2.1.0
  flutter_rating_bar: ^3.2.0+1
  slide_to_confirm: ^0.0.7
  video_player: ^2.1.10
  maps_launcher: ^2.0.1
  firebase_core: ^1.6.0
  firebase_auth: ^3.1.0
  intl: ^0.17.0
  images_picker: ^1.2.4
  audio_session: ^0.1.5
  get: ^4.3.4
  scrollable_positioned_list: ^0.1.10
  location: ^4.3.0
  flutter_animated_dialog: ^2.0.1
  map_launcher: ^2.1.1
  http: ^0.13.4
  flutter_stripe: ^1.2.0
  pay: ^1.0.5
  change_app_package_name: ^1.0.0
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.1.0+1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:
  better_video_player: ^1.0.4
flutter_icons:
  android: true
  image_path: "assets/tivele_capital.png"
  ios: true



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec


# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/videos/
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
